### ISSUE TITLE
SQL Alchemy migration

### ISSUE THREAD

**Issue by morgante** [getgrit/python#13]
We would like a migration to handle the upgrade to SQL Alchemy 2.0, from v1.3.

The migration guide is here: https://docs.sqlalchemy.org/en/20/changelog/migration_20.html
Note the bulk of the breaking changes were actually introduced behind a flag in 1.4: https://docs.sqlalchemy.org/en/14/changelog/migration_14.html

We started a basic preliminary pattern here: https://github.com/getgrit/python/blob/main/.grit/patterns/sql_alchemy_v2.md

But a lot of work is still needed on it to cover other cases.

## Acceptance criteria
1. Cover all the migration requirements / breaking changes in the pattern, with at least 10 sample test cases.
2. Find a significant open source application using SQL Alchemy using [Github code search](https://github.com/search?type=code&q=sqlalchemy%3D%3D1.3) and migrate it to 2.0. The automated migration should handle this completely.

Here are a few candidate repos. Emphasize one you can get up and testing quickly:
- https://github.com/wazuh/wazuh
- https://github.com/apache/superset

**Comment by morgante** [comment]
@SarthakSingh31 is working on this?

**Comment by SarthakSingh31** [comment]
@morgante I am still working on this. I wasn't able to do much the past few days due to being sick. I will try to get a pr up today.
