### ISSUE TITLE
OpenAI improvements

### ISSUE THREAD

**Issue by morgante** [getgrit/python#15]
Some improvements to the OpenAI migration we need to make:

- [x] For the removed methods, leave a warning/exception comment (exact language forthcoming)
- [x] For properties set on the client, we should convert them to throwing an exception:

```
        raise Exception("the `openai.$old_opt` option isn't read in the client API. you will need to pass it when you instantiate the client, e.g. `OpenAI($new_opt=$value)`")
```

**Comment by morgante** [comment]
@SarthakSingh31 Can you work on this?

**Comment by SarthakSingh31** [comment]
@morgante I can implement the second one pretty quickly. Isn't the first point already implemented?

**Comment by morgante** [comment]
Yes 1st part is done.
