### ISSUE TITLE
`ensure_imported` does not add import if there is a `from` import from the same module

### ISSUE THREAD

**Issue by vlopezferrando** [getgrit/python#26]
When you have an import of the form:

```python
from math import log
```

And then you want to ensure that `math` is imported with:

```grit
where {
    $import = "math",
    $import <: ensure_imported(),
}
```
You would expect that the resulting code is:

```
import math
from math import log
```

But the code is left as is, as the pattern does not match. [Here is a studio reproducing the issue](https://app.grit.io/studio?key=ami0bMkNlYXvtdrGapEJ5)

**Comment by morgante** [comment]
@vlopezferrando Up for trying to fix this? All the imports code is defined here: https://github.com/getgrit/python/blob/main/.grit/patterns/importing.md
